-- PostgreSQL schema. Apply this file before seed.sql.

CREATE TABLE plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    user_limit INTEGER NOT NULL CHECK (user_limit > 0),
    storage_limit_gb INTEGER NOT NULL CHECK (storage_limit_gb > 0),
    reports_per_month INTEGER NOT NULL CHECK (reports_per_month >= 0),
    support VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(120) NOT NULL,
    plan_id BIGINT NOT NULL REFERENCES plans(id),
    billing_cycle VARCHAR(20) NOT NULL CHECK (billing_cycle IN ('monthly', 'annual')),
    current_periodstart DATE NOT NULL,
    current_periodend DATE NOT NULL,
    amount_due NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (amount_due >= 0),
    last_payment_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (current_period_end > current_period_start)
);

CREATE INDEX subscriptions_customer_id_idx ON subscriptions(customer_id);
CREATE INDEX subscriptions_plan_id_idx ON subscriptions(plan_id);
